# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'pb-dev'
    subscriptionId: 'cbcd85be-00f1-44f4-a5a2-acdbf049d4db'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'pb-az-mpn-neu-net01-rg'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/indesol1959/ARMPipeline-repo/refs/heads/main/create_web_app/azuredeploy.json?token=GHSAT0AAAAAADAR4IN4L325XKEJ7MPNO7Y6Z6VQCMA'
    overrideParameters: '-projectName create_web_app'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'